
package calcufinal;

import java.util.ArrayList;

/**
 * Clase en donde se programa la interface gráfica (GUI) 
 * @author danieltena
 */

public class GUI2 extends javax.swing.JFrame {
    PilaA pila;
    int parentesisAbiertos;
    double newNumber;
    double numControl;
    int decimalControl;
    
    
    /**
     * Constructor de la clase GUI 2 
     * Creates new form GUI
     */
    public GUI2() {
        initComponents();
        pila = new PilaA(40);
        parentesisAbiertos = 0;
        decimalControl = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        botonParIzq = new javax.swing.JButton();
        botonParDer = new javax.swing.JButton();
        boton6 = new javax.swing.JButton();
        boton5 = new javax.swing.JButton();
        boton4 = new javax.swing.JButton();
        boton7 = new javax.swing.JButton();
        boton8 = new javax.swing.JButton();
        boton9 = new javax.swing.JButton();
        botonPunto = new javax.swing.JButton();
        boton0 = new javax.swing.JButton();
        botonMenos = new javax.swing.JButton();
        botonMas = new javax.swing.JButton();
        botonIgual = new javax.swing.JButton();
        boton1 = new javax.swing.JButton();
        boton2 = new javax.swing.JButton();
        boton3 = new javax.swing.JButton();
        botonDividir = new javax.swing.JButton();
        botonMult = new javax.swing.JButton();
        botonBorrar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cajaTexto = new javax.swing.JTextArea();
        botonPotencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        botonParIzq.setBackground(new java.awt.Color(204, 0, 0));
        botonParIzq.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        botonParIzq.setForeground(new java.awt.Color(255, 255, 255));
        botonParIzq.setText("(");
        botonParIzq.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonParIzq.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParIzqActionPerformed(evt);
            }
        });

        botonParDer.setBackground(new java.awt.Color(204, 0, 0));
        botonParDer.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        botonParDer.setForeground(new java.awt.Color(255, 255, 255));
        botonParDer.setText(")");
        botonParDer.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        botonParDer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonParDerActionPerformed(evt);
            }
        });

        boton6.setBackground(new java.awt.Color(0, 153, 0));
        boton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton6.setForeground(new java.awt.Color(255, 255, 255));
        boton6.setText("6");
        boton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton6ActionPerformed(evt);
            }
        });

        boton5.setBackground(new java.awt.Color(0, 153, 0));
        boton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton5.setForeground(new java.awt.Color(255, 255, 255));
        boton5.setText("5");
        boton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton5ActionPerformed(evt);
            }
        });

        boton4.setBackground(new java.awt.Color(0, 153, 0));
        boton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton4.setForeground(new java.awt.Color(255, 255, 255));
        boton4.setText("4");
        boton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton4ActionPerformed(evt);
            }
        });

        boton7.setBackground(new java.awt.Color(0, 153, 0));
        boton7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton7.setForeground(new java.awt.Color(255, 255, 255));
        boton7.setText("7");
        boton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton7ActionPerformed(evt);
            }
        });

        boton8.setBackground(new java.awt.Color(0, 153, 0));
        boton8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton8.setForeground(new java.awt.Color(255, 255, 255));
        boton8.setText("8");
        boton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton8ActionPerformed(evt);
            }
        });

        boton9.setBackground(new java.awt.Color(0, 153, 0));
        boton9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton9.setForeground(new java.awt.Color(255, 255, 255));
        boton9.setText("9");
        boton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton9ActionPerformed(evt);
            }
        });

        botonPunto.setBackground(new java.awt.Color(0, 153, 0));
        botonPunto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonPunto.setForeground(new java.awt.Color(255, 255, 255));
        botonPunto.setText(".");
        botonPunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPuntoActionPerformed(evt);
            }
        });

        boton0.setBackground(new java.awt.Color(0, 153, 0));
        boton0.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton0.setForeground(new java.awt.Color(255, 255, 255));
        boton0.setText("0");
        boton0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton0ActionPerformed(evt);
            }
        });

        botonMenos.setBackground(new java.awt.Color(204, 0, 0));
        botonMenos.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonMenos.setForeground(new java.awt.Color(255, 255, 255));
        botonMenos.setText("-");
        botonMenos.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMenosActionPerformed(evt);
            }
        });

        botonMas.setBackground(new java.awt.Color(204, 0, 0));
        botonMas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botonMas.setForeground(new java.awt.Color(255, 255, 255));
        botonMas.setText("+");
        botonMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMasActionPerformed(evt);
            }
        });

        botonIgual.setBackground(new java.awt.Color(204, 0, 0));
        botonIgual.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botonIgual.setForeground(new java.awt.Color(255, 255, 255));
        botonIgual.setText("=");
        botonIgual.setToolTipText("");
        botonIgual.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonIgual.setIconTextGap(1);
        botonIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonIgualActionPerformed(evt);
            }
        });

        boton1.setBackground(new java.awt.Color(0, 153, 0));
        boton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton1.setForeground(new java.awt.Color(255, 255, 255));
        boton1.setText("1");
        boton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton1ActionPerformed(evt);
            }
        });

        boton2.setBackground(new java.awt.Color(0, 153, 0));
        boton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton2.setForeground(new java.awt.Color(255, 255, 255));
        boton2.setText("2");
        boton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton2ActionPerformed(evt);
            }
        });

        boton3.setBackground(new java.awt.Color(0, 153, 0));
        boton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        boton3.setForeground(new java.awt.Color(255, 255, 255));
        boton3.setText("3");
        boton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boton3ActionPerformed(evt);
            }
        });

        botonDividir.setBackground(new java.awt.Color(204, 0, 0));
        botonDividir.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonDividir.setForeground(new java.awt.Color(255, 255, 255));
        botonDividir.setText("/");
        botonDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonDividirActionPerformed(evt);
            }
        });

        botonMult.setBackground(new java.awt.Color(204, 0, 0));
        botonMult.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        botonMult.setForeground(new java.awt.Color(255, 255, 255));
        botonMult.setText("*");
        botonMult.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonMultActionPerformed(evt);
            }
        });

        botonBorrar.setBackground(new java.awt.Color(204, 0, 0));
        botonBorrar.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        botonBorrar.setForeground(new java.awt.Color(255, 255, 255));
        botonBorrar.setText("AC");
        botonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonBorrarActionPerformed(evt);
            }
        });

        cajaTexto.setBackground(new java.awt.Color(204, 255, 153));
        cajaTexto.setColumns(20);
        cajaTexto.setRows(5);
        cajaTexto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                cajaTextoKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(cajaTexto);

        botonPotencia.setBackground(new java.awt.Color(204, 0, 0));
        botonPotencia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        botonPotencia.setForeground(new java.awt.Color(255, 255, 255));
        botonPotencia.setText("^");
        botonPotencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPotencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonPotenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(boton1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(boton3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(botonParIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonParDer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(botonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(botonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(botonMult, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addComponent(botonPotencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(137, 137, 137))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonParIzq, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(botonParDer, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonBorrar, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonPotencia, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonMult, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boton6, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton4, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boton5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonDividir, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonMenos, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(boton7, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boton8, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boton9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botonIgual, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(botonPunto, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(boton0, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(botonMas, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53))
        );

        pack();
    }// </editor-fold>    
    
    // Asignacion de valores a los botones de la calculadora

    private void botonParIzqActionPerformed(java.awt.event.ActionEvent evt) {                                            
        cajaTexto.append("(");
        if(!pila.isEmpty()) {
            if(pila.peek() instanceof Character && (char)pila.peek() != ')') {
                pila.push('(');
                parentesisAbiertos++;
                decimalControl = 1;
            }
        }
        else {
            pila.push('(');
            parentesisAbiertos++;
            decimalControl = 1;
        }
    }                                           

    private void botonParDerActionPerformed(java.awt.event.ActionEvent evt) {                                            
        cajaTexto.append(")");
        if(parentesisAbiertos > 0 && !pila.isEmpty() && pila.peek() instanceof Double) {
            pila.push(')');
            parentesisAbiertos--;
            decimalControl = 1;
        }
    }                                           

    private void boton6ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        cajaTexto.append("6");
        newNumber = 6.0;
        if (pila.isEmpty() || (pila.peek() instanceof Character && (char)pila.peek() != ')'))
            pila.push(newNumber);
        else if (pila.peek() instanceof Double) {
            numControl = (Double)pila.pop();
            numControl = numControl * 10 + newNumber / decimalControl;
            if(decimalControl > 1)
                decimalControl = decimalControl * 10;
        }
        
    }                                      

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        cajaTexto.append("5");
        newNumber = 5.0;
        if (pila.isEmpty() || (pila.peek() instanceof Character && (char)pila.peek() != ')'))
            pila.push(newNumber);
        else if (pila.peek() instanceof Double) {
            numControl = (Double)pila.pop();
            numControl = numControl * 10 + newNumber / decimalControl;
            if(decimalControl > 1)
                decimalControl = decimalControl * 10;
        }
    }                                      
                           

    private void boton4ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        cajaTexto.append("4");
        newNumber = 4.0;
        if (pila.isEmpty() || (pila.peek() instanceof Character && (char)pila.peek() != ')'))
            pila.push(newNumber);
        else if (pila.peek() instanceof Double) {
            numControl = (Double)pila.pop();
            numControl = numControl * 10 + newNumber / decimalControl;
            if(decimalControl > 1)
                decimalControl = decimalControl * 10;
        }
    }                                        

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        cajaTexto.append("7");
        newNumber = 7.0;
        if (pila.isEmpty() || (pila.peek() instanceof Character && (char)pila.peek() != ')'))
            pila.push(newNumber);
        else if (pila.peek() instanceof Double) {
            numControl = (Double)pila.pop();
            numControl = numControl * 10 + newNumber / decimalControl;
            if(decimalControl > 1)
                decimalControl = decimalControl * 10;
        }    
    }                                           

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        cajaTexto.append("8");
        newNumber = 8.0;
        if (pila.isEmpty() || (pila.peek() instanceof Character && (char)pila.peek() != ')'))
            pila.push(newNumber);
        else if (pila.peek() instanceof Double) {
            numControl = (Double)pila.pop();
            numControl = numControl * 10 + newNumber / decimalControl;
            if(decimalControl > 1)
                decimalControl = decimalControl * 10;
        }
    }                                   

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        cajaTexto.append("9");
        newNumber = 9.0;
        if (pila.isEmpty() || (pila.peek() instanceof Character && (char)pila.peek() != ')'))
            pila.push(newNumber);
        else if (pila.peek() instanceof Double) {
            numControl = (Double)pila.pop();
            numControl = numControl * 10 + newNumber / decimalControl;
            if(decimalControl > 1)
                decimalControl = decimalControl * 10;
        }
    }                                      

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {                                          
       cajaTexto.append(".");
        if(!pila.isEmpty() && pila.peek() instanceof Double && decimalControl == 1)
            decimalControl = 10;
    }                                       

    private void boton0ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        cajaTexto.append("0");
        newNumber = 0.0;
        if (pila.isEmpty() || (pila.peek() instanceof Character && (char)pila.peek() != ')'))
            pila.push(newNumber);
        else if (pila.peek() instanceof Double) {
            numControl = (Double)pila.pop();
            numControl = numControl * 10 + newNumber / decimalControl;
            if(decimalControl > 1)
                decimalControl = decimalControl * 10;
        }
    }                                   

    private void botonMenosActionPerformed(java.awt.event.ActionEvent evt) {                                          
        cajaTexto.append("-");
    }                                          

    private void botonMasActionPerformed(java.awt.event.ActionEvent evt) {                                        
        cajaTexto.append("+");
    }                                        

    // Metodo que calcula el valor que arroja la calculadora
    private double prueba (Calculadora calc, PilaA postfija){
        double res;
        res = calc.calculaPostFija(postfija);
        return res;
    }
    
    private void botonIgualActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // Ingresa lo que el usuario escribe a la pila
        for(int i=0; i<cajaTexto.getText().length(); i++){
            pila.push(cajaTexto.getText().charAt(i));
        }
        // Revisa que los parentesis esten correctos
        if(parentesisAbiertos == 0) {
            Calculadora calc = new Calculadora();
            // Utiliza el metodo de validar para ver si el calculo procede o si no arroja error
            if (!validar()){
                PilaA postfija = calc.convPostfija(pila);
                double res;
                res = prueba(calc, postfija);
                cajaTexto.setText(""+ res);
            }
            else
                cajaTexto.setText("ERROR");
        }
    }                                          

    // Metodo que valida la sintaxis del input del usuario
    public boolean validar() {
    ArrayList<Character> operacion = new ArrayList<Character>();

    boolean error = false;

    // Transformamos el getText a ArrayList
    for (int i = 0; i < cajaTexto.getText().length(); i++) {
        operacion.add(cajaTexto.getText().charAt(i));
    }

    // Revisa la escritura del usuario en caso de que este mal 
    for (int i = 0; i < operacion.size() - 1 && !error; i++) {
        char currentChar = operacion.get(i);
        char nextChar = operacion.get(i + 1);

        if (esOperador(currentChar) && esOperador(nextChar)) {
            
            error = true;
        }

        if (currentChar == '-' && esOperadorDespues(nextChar)) {
            
            error = true;
        }

        if ((esOperador(currentChar) || currentChar == '-') && esOperadorDespues(nextChar)) {
            
            error = true;
        }
    }

    return error;
}

// Metodo auxiliar para verificar si un carácter es un operador
private boolean esOperador(char c) {
    return c == '+' || c == '-' || c == '*' || c == '/' || c == '^';
}

// Metodo auxiliar para verificar si después de '-' hay un operador
private boolean esOperadorDespues(char c) {
    return esOperador(c) || c == '+' || c == '/' || c == '*' || c == '^';
}
    
    private void boton1ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        cajaTexto.append("1");
        newNumber = 1.0;
        if (pila.isEmpty() || (pila.peek() instanceof Character && (char)pila.peek() != ')'))
            pila.push(newNumber);
        else if (pila.peek() instanceof Double) {
            numControl = (Double)pila.pop();
            numControl = numControl * 10 + newNumber / decimalControl;
            if(decimalControl > 1)
                decimalControl = decimalControl * 10;
        }
    }                                        

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        cajaTexto.append("2");
        newNumber = 2.0;
        if (pila.isEmpty() || (pila.peek() instanceof Character && (char)pila.peek() != ')'))
            pila.push(newNumber);
        else if (pila.peek() instanceof Double) {
            numControl = (Double)pila.pop();
            numControl = numControl * 10 + newNumber / decimalControl;
            if(decimalControl > 1)
                decimalControl = decimalControl * 10;
        }
    }                                           

    private void boton3ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        cajaTexto.append("3");
        newNumber = 3.0;
        if (pila.isEmpty() || (pila.peek() instanceof Character && (char)pila.peek() != ')'))
            pila.push(newNumber);
        else if (pila.peek() instanceof Double) {
            numControl = (Double)pila.pop();
            numControl = numControl * 10 + newNumber / decimalControl;
            if(decimalControl > 1)
                decimalControl = decimalControl * 10;
        }
    }                                       

    private void botonDividirActionPerformed(java.awt.event.ActionEvent evt) {                                            
        cajaTexto.append("/");
    }                                            

    private void botonBorrarActionPerformed(java.awt.event.ActionEvent evt) {                                            
        cajaTexto.setText("");
    }                                          

    private void cajaTextoKeyTyped(java.awt.event.KeyEvent evt) {                                  
        // TODO add your handling code here:
    }                                  

    private void botonMultActionPerformed(java.awt.event.ActionEvent evt) {                                          
        cajaTexto.append(("*"));        // TODO add your handling code here:
    }                                        

    private void botonPotenciaActionPerformed(java.awt.event.ActionEvent evt) {                                              
        cajaTexto.append("^");// TODO add your handling code here:
    }                                            

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                    
    private javax.swing.JButton boton0;
    private javax.swing.JButton boton1;
    private javax.swing.JButton boton2;
    private javax.swing.JButton boton3;
    private javax.swing.JButton boton4;
    private javax.swing.JButton boton5;
    private javax.swing.JButton boton6;
    private javax.swing.JButton boton7;
    private javax.swing.JButton boton8;
    private javax.swing.JButton boton9;
    private javax.swing.JButton botonBorrar;
    private javax.swing.JButton botonDividir;
    private javax.swing.JButton botonIgual;
    private javax.swing.JButton botonMas;
    private javax.swing.JButton botonMenos;
    private javax.swing.JButton botonMult;
    private javax.swing.JButton botonParDer;
    private javax.swing.JButton botonParIzq;
    private javax.swing.JButton botonPotencia;
    private javax.swing.JButton botonPunto;
    private javax.swing.JTextArea cajaTexto;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration                  
}